### ISSUE TITLE
Add support for more operating systems!

### ISSUE THREAD

**Issue by hansgru** [kohsuke/akuma#7]
Please add support for more operating systems (e.g. AIX and Windows)

#6 would allow that, since the new JNA library has support for many more operating systems now, but you library seems to be hardcoded to 
```
       if("Linux".equals(os))
            return ofLinux(pid);
        if("SunOS".equals(os))
            return ofSolaris(pid);
        if("Mac OS X".equals(os))
            return ofMac(pid);
```
only.

**Comment by rodrigo815** [comment]
Looking forward to it.

My code throws `UnsupportedOperationException` with message "Unsupported Operating System Windows 10",

`Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported Operating System Windows 10
        at com.sun.akuma.JavaVMArguments.of(JavaVMArguments.java:112)
        at com.sun.akuma.JavaVMArguments.current(JavaVMArguments.java:92)
        at com.sun.akuma.Daemon.daemonize(Daemon.java:106)`
